name: atividade
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0
  boolean_selector: ^2.1.2
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8     
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.11.1
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  stack_trace: ^1.12.1
  stream_channel: ^2.1.4
  string_scanner: ^1.4.1
  term_glyph: ^1.2.2
  test_api: ^0.7.4
  vm_service: ^15.0.0  
  yaml: ^3.1.0
  firebase_core: ^3.12.0
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true