// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLqmQCVq_Bh3qaXS7DHVR6Zxh54AuuxI',
    appId: '1:535861841816:web:1068a237711ef0a24365ed',
    messagingSenderId: '535861841816',
    projectId: 'flutter-firabase-7fa8b',
    authDomain: 'flutter-firabase-7fa8b.firebaseapp.com',
    storageBucket: 'flutter-firabase-7fa8b.firebasestorage.app',
    measurementId: 'G-KTKK3X423X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2DvuVfL3MrI9HVIRCIXGmpl0csRWm934',
    appId: '1:535861841816:android:a3573e437ec504524365ed',
    messagingSenderId: '535861841816',
    projectId: 'flutter-firabase-7fa8b',
    storageBucket: 'flutter-firabase-7fa8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBim7bnaEDm5vaiKGaw-lZcbQSPDgKNWAI',
    appId: '1:535861841816:ios:c1b920d859e47ba74365ed',
    messagingSenderId: '535861841816',
    projectId: 'flutter-firabase-7fa8b',
    storageBucket: 'flutter-firabase-7fa8b.firebasestorage.app',
    iosClientId: '535861841816-0a69u16uailvjlejor4niv668cdr66uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.atividade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBim7bnaEDm5vaiKGaw-lZcbQSPDgKNWAI',
    appId: '1:535861841816:ios:c1b920d859e47ba74365ed',
    messagingSenderId: '535861841816',
    projectId: 'flutter-firabase-7fa8b',
    storageBucket: 'flutter-firabase-7fa8b.firebasestorage.app',
    iosClientId: '535861841816-0a69u16uailvjlejor4niv668cdr66uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.atividade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyLqmQCVq_Bh3qaXS7DHVR6Zxh54AuuxI',
    appId: '1:535861841816:web:12da27ecd7e701944365ed',
    messagingSenderId: '535861841816',
    projectId: 'flutter-firabase-7fa8b',
    authDomain: 'flutter-firabase-7fa8b.firebaseapp.com',
    storageBucket: 'flutter-firabase-7fa8b.firebasestorage.app',
    measurementId: 'G-RH8GSC22T1',
  );
}
